#cloud-config
hostname: lab-gw
manage_etc_hosts: true

users:
  - name: labadmin
    gecos: Lab Gateway Admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD...REPLACE_WITH_YOUR_PUBKEY...

package_update: true
package_upgrade: true
packages:
  - iptables-persistent
  - dnsmasq
  - net-tools
  - tcpdump
  - python3
  - curl
  - iproute2

write_files:
  # Netplan config: eth0 static, eth1 DHCP
  - path: /etc/netplan/50-lab-network.yaml
    permissions: '0644'
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          eth0:
            dhcp4: no
            addresses: [10.0.100.1/24]
            nameservers:
              addresses: [127.0.0.1]
          eth1:
            dhcp4: yes

  # dnsmasq lab mapping
  - path: /etc/dnsmasq.d/lab.conf
    permissions: '0644'
    content: |
      listen-address=127.0.0.1,10.0.100.1
      bind-interfaces
      no-resolv
      server=8.8.8.8
      # Replace with your real cloud login IP
      address=/login.cloud.example/203.0.113.45
      cache-size=1000

  # iptables lock-down script
  - path: /usr/local/sbin/lab-iptables.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -euo pipefail

      CLOUD_IP="203.0.113.45"   # <<< REPLACE if needed
      LAB_SUBNET="10.0.100.0/24"
      IF_LAB="eth0"
      IF_EXT="eth1"

      iptables -F
      iptables -t nat -F
      iptables -X

      iptables -P FORWARD DROP
      iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      iptables -A FORWARD -s ${LAB_SUBNET} -d ${CLOUD_IP} -i ${IF_LAB} -o ${IF_EXT} -p tcp --dport 443 -m conntrack --ctstate NEW -j ACCEPT
      iptables -A FORWARD -s ${LAB_SUBNET} -o ${IF_EXT} -j DROP

      iptables -t nat -A POSTROUTING -s ${LAB_SUBNET} -d ${CLOUD_IP} -o ${IF_EXT} -j MASQUERADE

      if command -v netfilter-persistent >/dev/null 2>&1; then
        netfilter-persistent save
      else
        iptables-save > /etc/iptables/rules.v4 || true
      fi

      echo "Applied iptables: lab subnet -> ${CLOUD_IP}:443 via ${IF_EXT}"

  # egress watchdog script
  - path: /usr/local/bin/egress-watchdog.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -euo pipefail

      CLOUD_IP="203.0.113.45"
      CHECK_PORT=443
      LAB_NET="10.0.100.0/24"

      check_conn() {
        timeout 3 bash -c "cat < /dev/null > /dev/tcp/${CLOUD_IP}/${CHECK_PORT}" >/dev/null 2>&1
      }

      apply_fail_closed() {
        if ! iptables -C FORWARD -s ${LAB_NET} -j DROP >/dev/null 2>&1; then
          iptables -I FORWARD 1 -s ${LAB_NET} -j DROP
          logger -t egress-watchdog "Egress down: fail-closed applied"
        fi
      }

      remove_fail_closed() {
        while iptables -C FORWARD -s ${LAB_NET} -j DROP >/dev/null 2>&1; do
          iptables -D FORWARD -s ${LAB_NET} -j DROP || break
          logger -t egress-watchdog "Egress up: fail-closed removed"
        done
      }

      if check_conn; then
        remove_fail_closed
      else
        apply_fail_closed
      fi

  # systemd unit for watchdog
  - path: /etc/systemd/system/egress-watchdog.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Egress Watchdog (fail-closed)
      After=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/egress-watchdog.sh

      [Install]
      WantedBy=multi-user.target

  # systemd timer
  - path: /etc/systemd/system/egress-watchdog.timer
    permissions: '0644'
    content: |
      [Unit]
      Description=Run egress-watchdog every 10s

      [Timer]
      OnUnitActiveSec=10s
      AccuracySec=1s

      [Install]
      WantedBy=timers.target

runcmd:
  - [ sh, -c, "netplan apply || true" ]
  - [ sh, -c, "systemctl enable --now dnsmasq || true" ]
  - [ sh, -c, "chmod +x /usr/local/sbin/lab-iptables.sh && /usr/local/sbin/lab-iptables.sh || true" ]
  - [ sh, -c, "systemctl daemon-reload || true" ]
  - [ sh, -c, "systemctl enable --now egress-watchdog.timer || true" ]
  - [ sh, -c, "echo 'LAB-GW ready: eth0=10.0.100.1, eth1=DHCP, egress locked to 203.0.113.45:443' > /etc/motd" ]

final_message: |
  LAB-GW bootstrap finished.
  * Replace SSH key above with your own before ISO build.
  * Verify iptables rules with: sudo iptables -L -v -n
  * Verify watchdog: sudo systemctl status egress-watchdog.timer